<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NSLabs.EFCore.Extensions</RootNamespace>
    <PackageId>NSLabs.EFCore.Extensions.SqlServer</PackageId>
    <Description>SQL Server provider for NSLabs.EFCore.Extensions</Description>
    <NoWarn>CA2255</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSLabs.EFCore.Extensions\NSLabs.EFCore.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration" />
  </ItemGroup>

</Project>
