<Project Sdk="Microsoft.NET.Sdk">

  <!-- xUnit.net v3 test projects must be executables. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="NSLabs.EFCore.Extensions.Tests.Common" />
    <Using Include="NSLabs.EFCore.Extensions.Tests.Integration.Shared" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSLabs.EFCore.Extensions.Tests.Common\NSLabs.EFCore.Extensions.Tests.Common.csproj" />
    <ProjectReference Include="..\NSLabs.EFCore.Extensions.Tests.Integration.Shared\NSLabs.EFCore.Extensions.Tests.Integration.Shared.csproj" />
    <ProjectReference Include="..\..\src\NSLabs.EFCore.Extensions\NSLabs.EFCore.Extensions.csproj" />
    <ProjectReference Include="..\..\src\NSLabs.EFCore.Extensions.Sqlite\NSLabs.EFCore.Extensions.Sqlite.csproj" />
  </ItemGroup>

</Project>
