<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NSLabs.EFCore.Extensions</RootNamespace>
    <PackageId>NSLabs.EFCore.Extensions</PackageId>
    <!-- Description inherited from Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.SqlServer" />
  </ItemGroup>

</Project>
