<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NSLabs.EFCore.Extensions</RootNamespace>
    <PackageId>NSLabs.EFCore.Extensions</PackageId>
    <IsPackable>true</IsPackable>
    <!-- Description inherited from Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.SqlServer" />
  </ItemGroup>

</Project>
