<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NSLabs.EFCore.Extensions</RootNamespace>
    <PackageId>NSLabs.EFCore.Extensions</PackageId>
    <IsPackable>true</IsPackable>
    <!-- Description inherited from Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Common" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.Shared" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.Shared" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.SqlServer" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.Sqlite" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.SqlServer" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.Sqlite" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.SqlServer" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Sqlite" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Npgsql" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.Npgsql" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.Npgsql" />
  </ItemGroup>

</Project>
