<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NSLabs.EFCore.Extensions</RootNamespace>
    <PackageId>NSLabs.EFCore.Extensions.Sqlite</PackageId>
    <Description>SQLite provider for NSLabs.EFCore.Extensions</Description>
    <NoWarn>CA2255</NoWarn>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSLabs.EFCore.Extensions\NSLabs.EFCore.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Common" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.Shared" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.Shared" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.SqlServer" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Unit.Sqlite" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.SqlServer" />
    <InternalsVisibleTo Include="NSLabs.EFCore.Extensions.Tests.Integration.Sqlite" />
  </ItemGroup>

</Project>
